# Generated by Django 3.1.2 on 2020-10-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postmovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_description', models.TextField()),
                ('movie_file', models.FileField(upload_to='media/movies')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('Director_Name', models.CharField(max_length=100)),
                ('Actors_Name', models.CharField(max_length=100)),
                ('Published_date', models.DateTimeField(blank=True, null=True)),
                ('Thumbnail', models.ImageField(upload_to='media/gallery')),
            ],
        ),
    ]
