# Generated by Django 3.1.2 on 2020-10-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Management_System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmovie',
            name='Published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmovie',
            name='movie_file',
            field=models.FileField(upload_to='media/movies'),
        ),
    ]
