# Generated by Django 3.1.2 on 2020-10-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Management_System', '0003_auto_20201021_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmovie',
            name='movie_file',
            field=models.FileField(upload_to='media'),
        ),
    ]
