# Generated by Django 3.1.2 on 2020-11-03 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movie_Management_System', '0004_auto_20201025_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmovie',
            name='Publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
