# Generated by Django 3.1.2 on 2020-11-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Management_System', '0005_postmovie_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmovie',
            name='Publisher',
        ),
    ]
